### ISSUE TITLE
StackOverflowError when bulk-deleting many mailboxes at once

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XCMailr#62]
When deleting a lot (i.e. thousands) of mailboxes at once via the UI, the following error may appear:

```
2019-09-30 20:01:35 ERROR n.NinjaDefault:232 - Emitting bad request 500. Something really wrong when calling route: /mail/bulkDelete (class: class controllers.BoxHandler method: public ninja.Result controllers.BoxHandler.bulkDeleteBoxes(java.lang.Object,ninja.Context))
java.lang.RuntimeException: java.lang.StackOverflowError
	at ninja.params.ControllerMethodInvoker.invoke(ControllerMethodInvoker.java:83) ~[ninja-core-6.3.0.jar:na]
	at ninja.FilterChainEnd.next(FilterChainEnd.java:45) ~[ninja-core-6.3.0.jar:na]
	at filters.JsonSecureFilter.filter(JsonSecureFilter.java:72) ~[classes/:na]
	at ninja.FilterChainImpl.next(FilterChainImpl.java:36) ~[ninja-core-6.3.0.jar:na]
	at ninja.NinjaDefault.onRouteRequest(NinjaDefault.java:102) ~[ninja-core-6.3.0.jar:na]
	at ninja.servlet.NinjaServletDispatcher.service(NinjaServletDispatcher.java:86) [ninja-servlet-6.3.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:na]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) [jetty-util-6.1.26.jar:6.1.26]
Caused by: java.lang.StackOverflowError: null
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:130) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:130) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:130) ~[h2-1.4.196.jar:1.4.196]
    ...
```

Looks like the delete query is too complex. It ORs the IDs of the to-be-deleted mailboxes, i.e. "ID=xxx OR ID=yyy OR ...". Maybe an "ID IN (xxx, yyy, ...)" is more appropriate here. Additionally, the list of mailboxes should be processed in chunks of, say, 1000 elements.

**Comment by jowerner** [comment]
All other bulk actions (enable, disable, reset, ...) are affected the same way.

**Comment by jowerner** [comment]
See also: https://github.com/h2database/h2database/issues/1887

**Comment by jowerner** [comment]
Now all bulk actions process mailboxes in chunks of 1000 and use the IN operator in the WHERE clause.
