### ISSUE TITLE
Constraint violation when deleting mailboxes

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XCMailr#65]
Deleting a mailbox which still contains some temporary mails is not possible. The server complains with the following exception:

```
javax.persistence.PersistenceException: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "FK_MAIL_MAILBOX_2: PUBLIC.MAIL FOREIGN KEY(MAILBOX_ID) REFERENCES PUBLIC.MAILBOXES(ID) (91521)"; SQL statement:
delete from mailboxes where id = ?  [23503-196]
        at com.avaje.ebeaninternal.server.persist.ExeUpdateSql.execute(ExeUpdateSql.java:76) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeSqlUpdate(DefaultPersistExecute.java:115) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.core.PersistRequestUpdateSql.executeNow(PersistRequestUpdateSql.java:44) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.core.PersistRequest.executeStatement(PersistRequest.java:74) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.core.PersistRequestUpdateSql.executeOrQueue(PersistRequestUpdateSql.java:49) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.executeSqlUpdate(DefaultPersister.java:139) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:541) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:445) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1782) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1774) ~[avaje-ebeanorm-3.2.5.jar:na]
        at com.avaje.ebean.Ebean.delete(Ebean.java:603) ~[avaje-ebeanorm-3.2.5.jar:na]
        at models.MBox.delete(MBox.java:422) ~[classes/:na]
        at controllers.BoxHandler.deleteBoxByJson(BoxHandler.java:460) ~[classes/:na]
```

This happens if the database is new (i.e. during development). For "older" databases (such as our live database) this issue may not appear, but this may be due to the fact that the corresponding foreign-key constraint was not correctly applied during database migration.

**Comment by h-arlt** [comment]
Fixed. Please recheck.
