### ISSUE TITLE
ExpirationService fails with PersistenceException

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XCMailr#66]
Found this in the log:

```
2019-12-17 04:13:03 ERROR c.ExpirationService:173 - Couldn't create new message statistics entry: models.MailStatisticsKey@e8d6cb76=etc.StatisticsEntry@5c9c046b
javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[NULL not allowed for column "FROM_DOMAIN"; SQL statement:\n insert into MAIL_STATISTICS (date, QUARTER_HOUR, FROM_DOMAIN, TARGET_DOMAIN, DROP_COUNT, FORWARD_COUNT) values (?,?,?,?,?,?) [23502-196]]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:97) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:57) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:66) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:448) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:478) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:335) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:310) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:280) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:248) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1568) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1558) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebean.Ebean.save(Ebean.java:453) ~[avaje-ebeanorm-3.2.5.jar:na]
	at controllers.ExpirationService.run(ExpirationService.java:169) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_222]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
Caused by: org.h2.jdbc.JdbcSQLException: NULL not allowed for column "FROM_DOMAIN"; SQL statement:
insert into MAIL_STATISTICS (date, QUARTER_HOUR, FROM_DOMAIN, TARGET_DOMAIN, DROP_COUNT, FORWARD_COUNT) values (?,?,?,?,?,?) [23502-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:345) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:797) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.dml.Insert.insertRows(Insert.java:151) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.dml.Insert.update(Insert.java:114) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.CommandContainer.update(CommandContainer.java:101) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.command.Command.executeUpdate(Command.java:260) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:164) ~[h2-1.4.196.jar:1.4.196]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:150) ~[h2-1.4.196.jar:1.4.196]
	at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.executeUpdate(ExtendedPreparedStatement.java:147) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:55) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:134) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:86) ~[avaje-ebeanorm-3.2.5.jar:na]
	... 19 common frames omitted
```

**Comment by h-arlt** [comment]
Expiration did not check source domain of a given mail transaction to be non-null. Adapted code to do so.
