### ISSUE TITLE
Database connection issues

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XCMailr#70]
After a while the log file is full with entries like this one:

```
2020-04-28 00:46:05 ERROR o.s.s.s.Session:165 - Unexpected error in the SMTP handler thread
javax.persistence.PersistenceException: java.sql.SQLException: Unsuccessfully waited [1000] millis for a connection to be returned. No connections are free. You need to Increase the max connections of [25] or look for a connection pool leak using datasource.xxx.capturestacktrace=true
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:339) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:2018) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:178) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1459) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findUnique(DefaultServer.java:1230) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findUnique(DefaultOrmQuery.java:903) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.util.DefaultExpressionList.findUnique(DefaultExpressionList.java:193) ~[avaje-ebeanorm-3.2.5.jar:na]
	at models.MBox.getByName(MBox.java:450) ~[classes/:na]
	at controllers.MessageListener.doMboxPreconditionChecks(MessageListener.java:221) ~[classes/:na]
	at controllers.MessageListener.deliver(MessageListener.java:254) ~[classes/:na]
	at org.subethamail.smtp.helper.SimpleMessageListenerAdapter$Handler.data(SimpleMessageListenerAdapter.java:142) ~[subethasmtp-3.1.7.jar:June 16 2012]
	at org.subethamail.smtp.command.DataCommand.execute(DataCommand.java:64) ~[subethasmtp-3.1.7.jar:June 16 2012]
	at org.subethamail.smtp.server.RequireTLSCommandWrapper.execute(RequireTLSCommandWrapper.java:30) ~[subethasmtp-3.1.7.jar:June 16 2012]
	at org.subethamail.smtp.server.CommandHandler.handleCommand(CommandHandler.java:99) ~[subethasmtp-3.1.7.jar:June 16 2012]
	at org.subethamail.smtp.server.Session.runCommandLoop(Session.java:244) ~[subethasmtp-3.1.7.jar:June 16 2012]
	at org.subethamail.smtp.server.Session.run(Session.java:145) ~[subethasmtp-3.1.7.jar:June 16 2012]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
Caused by: java.sql.SQLException: Unsuccessfully waited [1000] millis for a connection to be returned. No connections are free. You need to Increase the max connections of [25] or look for a connection pool leak using datasource.xxx.capturestacktrace=true
	at com.avaje.ebeaninternal.server.lib.sql.PooledConnectionQueue._getPooledConnectionWaitLoop(PooledConnectionQueue.java:314) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.lib.sql.PooledConnectionQueue._getPooledConnection(PooledConnectionQueue.java:288) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.lib.sql.PooledConnectionQueue.getPooledConnection(PooledConnectionQueue.java:228) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.getPooledConnection(DataSourcePool.java:675) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.getConnection(DataSourcePool.java:663) ~[avaje-ebeanorm-3.2.5.jar:na]
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:313) ~[avaje-ebeanorm-3.2.5.jar:na]
	... 18 common frames omitted
```

Looks like the XCMailr user interface is responsive, but background tasks may not run any longer. 

We need to investigate what is going on here. Either the number of database connections is too low for the workload or we have a connection leak.

**Comment by jowerner** [comment]
We did not find an obvious connection leak. Further investigations have shown that the database simply gets slower the more mailboxes are created, so under load all available database connections were indeed busy. After deleting any unused mailboxes and increasing the number of database connections from 25 to 50, the exception could not be observed any longer.
